import type { Skill } from 'mu-harness';

// Skill bodies use single-quoted lines (backticks stay literal) and `~~~` code
// fences (so they don't collide with markdown's ``` in the model's view).
const lines = (...l: string[]): string => l.join('\n');

const MANAGE_TASK = lines(
  'Scheduled tasks are YAML files at `definitions/tasks/<id>.yaml` (one task per file). They hot-reload — no restart for any action below.',
  '',
  '**Create** — use `write` to add a file:',
  '- `id` (required): unique id (letters/digits/`-`/`_`); also the filename.',
  '- `cron` (required): cron expression, e.g. "0 9 * * *" (5 fields) or with leading seconds (6 fields). Check the field count and ranges.',
  '- `prompt` (required): the instruction handed to the agent on each run.',
  '- `agent` (optional): which agent runs it (defaults to the primary agent).',
  '- `timezone` (optional): IANA timezone, e.g. "Europe/Paris".',
  '',
  '~~~yaml',
  'id: daily-standup',
  'cron: "0 9 * * *"',
  'prompt: Summarize the latest commits.',
  'agent: arya',
  '~~~',
  '',
  '**Edit** — `read` the file, then `edit` it (or `write` the full new content). Keep `id` matching the filename.',
  '**Delete** — remove the file.',
);

const MANAGE_AGENT = lines(
  'Sub-agents are Markdown files at `definitions/agents/<name>.md`. They hot-reload — delegatable via `subagent`, no restart for any action below.',
  '',
  '**Create** — use `write` to add a file. Frontmatter:',
  '- `name` (required): kebab-case; also the filename.',
  '- `description` (required): one line — shown in the delegation roster.',
  '- `color` (optional): hex, e.g. "#10B981".',
  '- `tools` (optional): per-tool grants — each tool maps to allow | ask | deny, or a nested {glob: decision} map. Omitted tools are denied; be least-privilege.',
  '',
  'The body is the system prompt. Example:',
  '~~~markdown',
  '---',
  'name: researcher',
  'description: Reads code and docs to answer focused questions.',
  'color: "#8B5CF6"',
  'tools:',
  '  read: allow',
  '  webfetch: allow',
  '  write: deny',
  '---',
  'You are a research sub-agent. Answer concisely, citing files.',
  '~~~',
  '',
  '**Edit** — `read` then `edit` (or `write`) the file. Keep `name` matching the filename.',
  '**Delete** — remove the file.',
);

const MANAGE_SKILL = lines(
  'Skills are `skills/<name>/SKILL.md` files. They hot-reload — loadable via `skill`, no restart for any action below.',
  '',
  '**Create** — use `write` to add `skills/<name>/SKILL.md`. Frontmatter:',
  '- `name` (required): kebab-case; must match the directory name.',
  '- `description` (required): one line on when to use it.',
  '',
  'The body is the instructions to follow. Example:',
  '~~~markdown',
  '---',
  'name: release-notes',
  'description: Draft release notes from the commit log since the last tag.',
  '---',
  '1. Run git log <last-tag>..HEAD --oneline.',
  '2. Group commits by type (feat / fix / chore).',
  '3. Write a concise changelog.',
  '~~~',
  '',
  '**Edit** — `read` then `edit` (or `write`) the SKILL.md. Keep `name` matching the directory.',
  '**Delete** — remove the skill directory.',
);

const UPDATE_CONFIG = lines(
  'Modify arya configuration. There are no settings-file hooks, no env block in config, and no MCP-in-config — those do not exist here (environment variables are reserved for plugin integrations via `.env`). Touch only the surfaces below.',
  '',
  '## Where config lives',
  '',
  '| Surface | Path | Holds | Edit how |',
  '|---|---|---|---|',
  '| Runtime config | `~/.config/arya/config.json` | `baseUrl`, `model`, `wsPort` (required); `wsHost`, `authToken`, `apiKey`, `kind`, `primaryAgent`, `maxTokens`, `temperature`, `streamTimeoutMs`, `capabilities` | edit JSON directly — validated at boot, so restart to apply |',
  '| Agent permissions | `definitions/agents/<name>.md` (project) or `~/.config/arya/agents/<name>.md` (global) | per-tool `allow` / `ask` / `deny` in the `tools` frontmatter | edit the file, or use the `manage-agent` skill — hot-reloads, no restart |',
  '| Scheduled tasks | `definitions/tasks/<id>.yaml` | cron jobs | use the `manage-task` skill — hot-reloads |',
  '| Skills | `skills/<name>/SKILL.md` | reusable workflows | use the `manage-skill` skill — hot-reloads |',
  '',
  '## CRITICAL: read before write, merge — do not replace',
  '',
  'Always `read` the target file first and merge changes in. For nested objects (`capabilities`) and the agent `tools` map, ADD to what is already there — never overwrite the whole object or file.',
  '',
  '## What to edit where',
  '',
  '- **`config.json`** — provider connection (`baseUrl`, `kind`, `apiKey`), `model`, generation settings (`maxTokens`, `temperature`, `streamTimeoutMs`), companion transport (`wsPort`, `wsHost`, `authToken`), and `capabilities` (vision/audio). Required: `baseUrl`, `model`, `wsPort` — arya refuses to start if any is missing.',
  '- **Agent file** — to change what a tool may do without prompting (the permissions analog; there is no allow/deny array). Prefer the `manage-agent` skill.',
  '- **Tasks / skills** — do NOT hand-roll; load `manage-task` or `manage-skill` and follow it.',
  '',
  '## Safety: companion exposure',
  '',
  'If `authToken` is empty AND `wsHost` is non-loopback, arya refuses to start. When binding beyond `127.0.0.1`, set a non-empty `authToken` in the same edit.',
  '',
  '## Clarify ambiguity first',
  '',
  'Ask the user in plain text when the request is ambiguous: which surface (config vs agent file), whether to add to or replace a value, and which value when several are plausible. Do not guess.',
  '',
  '## Workflow',
  '',
  '1. Clarify intent if ambiguous.',
  '2. `read` the target file.',
  '3. Merge carefully — preserve existing keys.',
  '4. `edit` the file (or `write` the full merged content if it does not exist yet — config.json lives at `~/.config/arya/config.json`).',
  '5. Confirm what changed. `config.json` is validated at boot, so a restart is needed; agent/task/skill files hot-reload live.',
  '',
  '## Example tasks',
  '',
  '**Enable image input** — `read` `config.json`, merge in `capabilities`, point `baseUrl`/`model` at a vision-capable model, restart:',
  '~~~json',
  '{',
  '  "baseUrl": "http://<vision-host>:8080/v1",',
  '  "model": "<a-vision-capable-model>",',
  '  "capabilities": { "vision": true }',
  '}',
  '~~~',
  '',
  '**Point at a different provider** — set `baseUrl` (include the `/v1` suffix) and `model` in `config.json`; restart.',
  '',
  '**Let a sub-agent run a command without prompting** — this is a permission, so edit the agent (or use `manage-agent`). In the agent `tools` map:',
  '~~~yaml',
  'tools:',
  '  bash:',
  '    "git *": allow',
  '    "**": ask',
  '~~~',
  '',
  '## Common mistakes',
  '',
  '- Replacing an object or whole file instead of merging.',
  '- Wrong surface: model/provider/ports belong in `config.json`; permissions belong in the agent file; recurring jobs belong in a task (via `manage-task`).',
  '- Invalid JSON — re-read after editing to confirm it still parses; arya will not start on a malformed `config.json`.',
  '- Editing without reading first.',
  '',
  '## Troubleshooting',
  '',
  '- arya will not start → a required field (`baseUrl` / `model` / `wsPort`) is missing, JSON is malformed, or `authToken` is empty while `wsHost` is non-loopback.',
  '- A `config.json` change has no effect → it is read at boot; restart arya.',
  '- A permission change is ignored → confirm you edited the agent that is actually active and that the `tools` glob matches (e.g. `"git *"`). Agent files hot-reload, so no restart is needed.',
);

export const BUILTIN_SKILLS: Skill[] = [
  {
    name: 'update-config',
    description:
      'View or change arya configuration — provider/model/ports/capabilities in config.json, and per-tool permissions in agent files. Use when asked to change a setting, switch provider, enable vision/audio, or adjust what an agent may do.',
    prompt: UPDATE_CONFIG,
  },
  {
    name: 'manage-task',
    description: 'Create, edit, or delete a scheduled (cron) task. Use for any recurring or timed work to automate.',
    prompt: MANAGE_TASK,
  },
  {
    name: 'manage-agent',
    description:
      'Create, edit, or delete a sub-agent (persona + tool permissions) to delegate to. Use for a reusable role.',
    prompt: MANAGE_AGENT,
  },
  {
    name: 'manage-skill',
    description: 'Create, edit, or delete a skill (a reusable workflow loaded on demand). Use to capture a procedure.',
    prompt: MANAGE_SKILL,
  },
];
